食事投稿アプリ完成
masatakamaekawa/meal_app pull request #1
Opened 2021-10-13 11:35 UTC by masatakamaekawa

ご確認をお願いいたします｡

2021-10-13 11:41 UTC, masatakamaekawa commented
<img width="1298" alt="一覧画面" src="https://user-images.githubusercontent.com/89436077/137125363-08a03595-d2d5-42c0-b2c8-30965e7b40a6.png">

<img width="1298" alt="詳細画面(ログイン中)(他人の記事)①" src="https://user-images.githubusercontent.com/89436077/137125535-155bb96c-2a41-42ed-bdd4-80d8fdd5a287.png">

<img width="1298" alt="詳細画面(ログイン中)(他人の記事)②" src="https://user-images.githubusercontent.com/89436077/137125613-4b4668af-7761-4570-91e0-627d6ab7162e.png">

<img width="1298" alt="詳細画面(ログイン中)(自分の記事)①" src="https://user-images.githubusercontent.com/89436077/137125710-ab0ffb6d-0c79-43a8-afcc-237cf4acfef4.png">

<img width="1298" alt="詳細画面(ログイン中)(自分の記事)②" src="https://user-images.githubusercontent.com/89436077/137125787-940690a2-5b66-4f3c-9c16-6ecf645b1503.png">

<img width="1298" alt="詳細画面(ログインしていない)①" src="https://user-images.githubusercontent.com/89436077/137125862-86424a35-c8ec-43d1-918c-9546e2707d5f.png">

<img width="1298" alt="詳細画面(ログインしていない)②" src="https://user-images.githubusercontent.com/89436077/137125918-34260c2c-9d7b-44eb-bac4-4b27efe00f01.png">

<img width="1298" alt="新規投稿画面" src="https://user-images.githubusercontent.com/89436077/137125992-9a47d07b-c1d5-434d-881a-bedb4d66b324.png">

<img width="1298" alt="編集画面" src="https://user-images.githubusercontent.com/89436077/137126021-538ac535-012d-4fcc-a58c-20170353587c.png">

2021-10-13 12:22 UTC, kazu-taka requested changes
@masatakamaekawa
コメントしたので修正お願いします:bow:

2021-10-13 12:22 UTC, kazu-taka commented on app/Http/Controllers/PostController.php
> +}
@masatakamaekawa 
インデントの修正と、ifやelseの前後のスペース修正をお願いします🙏

2021-10-13 12:22 UTC, kazu-taka commented on app/Http/Controllers/PostController.php
> +    }
@masatakamaekawa 
リレーションはモデルに記述するので、それぞれのモデルに記述するように修正お願いします！！

2021-10-13 12:22 UTC, kazu-taka commented on app/Http/Controllers/PostController.php
> +    }
モデルに記述しているようなので、こちらは削除して下さい！！

2021-10-13 12:22 UTC, kazu-taka commented on database/factories/PostFactory.php
> +            'category_id' => Arr::random(Arr::pluck(Post::all(), 'id')),
@masatakamaekawa 
モデルができているのであれば、inRandomOrderでランダムな値を取得できるので、次回以降試してみて下さい✨
https://webty.jp/staffblog/production/post-2184/

2021-10-13 12:22 UTC, kazu-taka commented on database/migrations/2021_10_10_174140_create_posts_table.php
> +            $table->integer('category_id');
@masatakamaekawa 
 category_idも外部キーになるので修正お願いします🙏

2021-10-13 12:22 UTC, kazu-taka commented on database/migrations/2021_10_11_143942_create_categories_table.php
> +            $table->string('name')->unique()->index();
@masatakamaekawa 
名前には特にユニークインデックスは付与しないくてもOKです！
nameで検索しているのであればインデックスは合っても良いです✨

2021-10-13 12:22 UTC, kazu-taka commented on database/migrations/2021_10_11_163321_create_likes_table.php
> +            $table->unsignedBigInteger('user_id')->nullable();
@masatakamaekawa 
post_idもuser_idもどちらも外部キーになるので修正お願いします！

2021-10-13 12:22 UTC, kazu-taka commented on app/Http/Controllers/LikeController.php
> +        return back();
@masatakamaekawa 
`=`の前後にスペースを入れて下さい！
また、backはなるべく使用せず、戻る画面が決まっているのであれば、そちらを指定して下さい✨

2021-10-13 12:22 UTC, kazu-taka commented on app/Http/Controllers/PostController.php
> +        $category_id = $request->category_id;
@masatakamaekawa 
モデルのfillableに追加しているので、こちらは不要ではないですか！？

2021-10-13 12:22 UTC, kazu-taka commented on routes/web.php
> +Route::get('/post/unlike/{post}', [LikeController::class, 'unlike'])->name('unlike');
@masatakamaekawa 
URLに動詞(unXXXやgetXXXX)は含めない方がよいので、resourceを使用して、Likeのstoreとdestroyだけ生成するようにして下さい！
またLikeはPostに紐付いているので、ブログアプリのコメントのように、ルーティングはネストするようにお願いします🙏

2021-10-13 12:22 UTC, kazu-taka commented
@masatakamaekawa 
VSCodeのフォーマッターを使用してインデント等を修正するようにして下さい✨

2021-10-14 01:41 UTC, kazu-taka requested changes
@masatakamaekawa 
インデント修正して頂いたらマージしてOKです👍

2021-10-14 01:41 UTC, kazu-taka commented on app/Http/Controllers/PostController.php
> +}
@masatakamaekawa 
インデントの修正お願いします:bow:

2021-10-14 01:48 UTC, merged